### ISSUE TITLE
Error converting nginx.json (just a test json)

### ISSUE THREAD

**Issue by noripcord** [kindly/flatterer#50]
the file: [nginx.json.zip](https://github.com/kindly/flatterer/files/12541529/nginx.json.zip)

% flatterer ~/Downloads/nginx.json nginxjson
[2023-09-06T19:09:56.765Z ERROR] Error: Value at array position 1 is not an object: value is `"libxcrypt"`
Traceback (most recent call last):
  File "/opt/homebrew/bin/flatterer", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/flatterer/__init__.py", line 314, in cli
    flatten(inputs,
  File "/opt/homebrew/lib/python3.11/site-packages/flatterer/__init__.py", line 140, in flatten
    flatten_rs(input, output_dir, csv, xlsx, sqlite, parquet,
RuntimeError: Error: Value at array position 1 is not an object: value is `"libxcrypt"`

Location:
    /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/convert/mod.rs:717:9

**Comment by kindly** [comment]
Thanks for the report.

Flatterer does not currently deal with arrays just under the top level, where the first item is an object and the future items are not objects, as it tries to stream lists of objects at that level.  This is the case for the `uses_from_macos` key in that JSON.  The streaming, is to deal with very large lists of data that can not fit in memory.

However, for this case, with small data, you can force the stream to happen at the top level by doing:

```flatterer --json-stream nginx.json nginxjson```

This will load the whole JSON into memory (not a problem here) and treat that list as just the JSON object in the result, unless you also use the ` --arrays-new-table` option.

**Comment by noripcord** [comment]
yeahh. tried that with the GUI and worked! thanxx
