### ISSUE TITLE
panic: assertion failed: self.is_char_boundary(new_len)

### ISSUE THREAD

**Issue by jpmckinney** [kindly/flatterer#58]
## To reproduce

```
env RUST_BACKTRACE=full flatterer --nocsv --xlsx --ndjson --force --threads 1 2023.jsonl.gz t
```

## Output

```
[2024-01-25T19:53:09.422Z INFO ] gzip reader
[2024-01-25T19:53:15.773Z INFO ] Finished processing 158794 value(s)
[2024-01-25T19:53:16.949Z INFO ] Writing final XLSX file
[2024-01-25T19:53:16.949Z INFO ]     Writing 158794 row(s) to sheet `main`
[2024-01-25T19:53:17.015Z WARN ] WARNING: Cell larger than 32767 chararcters which is too large for XLSX format. The cell will be truncated, so some data will be missing.
[2024-01-25T19:53:17.015Z WARN ] WARNING: Cell larger than 32767 chararcters which is too large for XLSX format. The cell will be truncated, so some data will be missing.
[2024-01-25T19:53:17.035Z WARN ] WARNING: Cell larger than 32767 chararcters which is too large for XLSX format. The cell will be truncated, so some data will be missing.
[2024-01-25T19:53:17.084Z WARN ] WARNING: Cell larger than 32767 chararcters which is too large for XLSX format. The cell will be truncated, so some data will be missing.
[2024-01-25T19:53:17.103Z WARN ] WARNING: Cell larger than 32767 chararcters which is too large for XLSX format. The cell will be truncated, so some data will be missing.
[2024-01-25T19:53:17.181Z WARN ] WARNING: Cell larger than 32767 chararcters which is too large for XLSX format. The cell will be truncated, so some data will be missing.
[2024-01-25T19:53:17.184Z WARN ] WARNING: Cell larger than 32767 chararcters which is too large for XLSX format. The cell will be truncated, so some data will be missing.
[2024-01-25T19:53:17.204Z WARN ] WARNING: Cell larger than 32767 chararcters which is too large for XLSX format. The cell will be truncated, so some data will be missing.
[2024-01-25T19:53:17.276Z WARN ] WARNING: Cell larger than 32767 chararcters which is too large for XLSX format. The cell will be truncated, so some data will be missing.
[2024-01-25T19:53:17.304Z WARN ] WARNING: Cell larger than 32767 chararcters which is too large for XLSX format. The cell will be truncated, so some data will be missing.
[2024-01-25T19:53:17.331Z WARN ] WARNING: Cell larger than 32767 chararcters which is too large for XLSX format. The cell will be truncated, so some data will be missing.
[2024-01-25T19:53:17.375Z WARN ] WARNING: Cell larger than 32767 chararcters which is too large for XLSX format. The cell will be truncated, so some data will be missing.
[2024-01-25T19:53:17.431Z WARN ] WARNING: Cell larger than 32767 chararcters which is too large for XLSX format. The cell will be truncated, so some data will be missing.
[2024-01-25T19:53:17.513Z WARN ] WARNING: Cell larger than 32767 chararcters which is too large for XLSX format. The cell will be truncated, so some data will be missing.
[2024-01-25T19:53:17.547Z WARN ] WARNING: Cell larger than 32767 chararcters which is too large for XLSX format. The cell will be truncated, so some data will be missing.
[2024-01-25T19:53:17.570Z WARN ] WARNING: Cell larger than 32767 chararcters which is too large for XLSX format. The cell will be truncated, so some data will be missing.
[2024-01-25T19:53:17.590Z WARN ] WARNING: Cell larger than 32767 chararcters which is too large for XLSX format. The cell will be truncated, so some data will be missing.
[2024-01-25T19:53:17.605Z WARN ] WARNING: Cell larger than 32767 chararcters which is too large for XLSX format. The cell will be truncated, so some data will be missing.
[2024-01-25T19:53:17.623Z WARN ] WARNING: Cell larger than 32767 chararcters which is too large for XLSX format. The cell will be truncated, so some data will be missing.
[2024-01-25T19:53:17.626Z WARN ] WARNING: Cell larger than 32767 chararcters which is too large for XLSX format. The cell will be truncated, so some data will be missing.
[2024-01-25T19:53:17.668Z WARN ] WARNING: Cell larger than 32767 chararcters which is too large for XLSX format. The cell will be truncated, so some data will be missing.
[2024-01-25T19:53:17.687Z WARN ] WARNING: Cell larger than 32767 chararcters which is too large for XLSX format. The cell will be truncated, so some data will be missing.
[2024-01-25T19:53:17.721Z WARN ] WARNING: Cell larger than 32767 chararcters which is too large for XLSX format. The cell will be truncated, so some data will be missing.
[2024-01-25T19:53:17.723Z WARN ] WARNING: Cell larger than 32767 chararcters which is too large for XLSX format. The cell will be truncated, so some data will be missing.
[2024-01-25T19:53:17.732Z WARN ] WARNING: Cell larger than 32767 chararcters which is too large for XLSX format. The cell will be truncated, so some data will be missing.
[2024-01-25T19:53:17.737Z WARN ] WARNING: Cell larger than 32767 chararcters which is too large for XLSX format. The cell will be truncated, so some data will be missing.
[2024-01-25T19:53:17.741Z WARN ] WARNING: Cell larger than 32767 chararcters which is too large for XLSX format. The cell will be truncated, so some data will be missing.
thread '<unnamed>' panicked at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/alloc/src/string.rs:1246:13:
assertion failed: self.is_char_boundary(new_len)
stack backtrace:
   0:        0x12ed121c0 - _bz_internal_error
   1:        0x12ed360e4 - _bz_internal_error
   2:        0x12ed0de08 - _bz_internal_error
   3:        0x12ed12000 - _bz_internal_error
   4:        0x12ed13684 - _bz_internal_error
   5:        0x12ed1339c - _bz_internal_error
   6:        0x12ed13bc8 - _bz_internal_error
   7:        0x12ed13a90 - _bz_internal_error
   8:        0x12ed1264c - _bz_internal_error
   9:        0x12ed1383c - _bz_internal_error
  10:        0x12eed2ecc - _bz_internal_error
  11:        0x12eed2f40 - _bz_internal_error
  12:        0x12d1b2efc - _PyInit_flatterer
  13:        0x12d1ab464 - _PyInit_flatterer
  14:        0x12d1b7620 - _PyInit_flatterer
  15:        0x12d00a288 - <unknown>
  16:        0x12d009e4c - <unknown>
  17:        0x12d008004 - <unknown>
  18:        0x12d008d48 - <unknown>
  19:        0x10310480c - _cfunction_vectorcall_FASTCALL_KEYWORDS
  20:        0x10319b528 - __PyEval_EvalFrameDefault
  21:        0x103190d74 - __PyEval_Vector
  22:        0x1030ba370 - __PyVectorcall_Call
  23:        0x10319b528 - __PyEval_EvalFrameDefault
  24:        0x103190d74 - __PyEval_Vector
  25:        0x1030ba370 - __PyVectorcall_Call
  26:        0x10319b528 - __PyEval_EvalFrameDefault
  27:        0x103190d74 - __PyEval_Vector
  28:        0x1030bca7c - _method_vectorcall
  29:        0x1030ba370 - __PyVectorcall_Call
  30:        0x10319b528 - __PyEval_EvalFrameDefault
  31:        0x103190d74 - __PyEval_Vector
  32:        0x1030bcb08 - _method_vectorcall
  33:        0x10319b528 - __PyEval_EvalFrameDefault
  34:        0x103190d74 - __PyEval_Vector
  35:        0x1030b9e10 - __PyObject_FastCallDictTstate
  36:        0x1030bab58 - __PyObject_Call_Prepend
  37:        0x103125bc0 - _slot_tp_call
  38:        0x1030b9ff8 - __PyObject_MakeTpCall
  39:        0x1031999ec - __PyEval_EvalFrameDefault
  40:        0x103190c44 - _PyEval_EvalCode
  41:        0x1031e3fa0 - _run_mod
  42:        0x1031e2494 - __PyRun_SimpleFileObject
  43:        0x1031e1f1c - __PyRun_AnyFileObject
  44:        0x103201324 - _Py_RunMain
  45:        0x1032016d4 - _pymain_main
  46:        0x103201774 - _Py_BytesMain
Traceback (most recent call last):
  File "bin/flatterer", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib/python3.11/site-packages/flatterer/__init__.py", line 315, in cli
    flatten(inputs,
  File "lib/python3.11/site-packages/flatterer/__init__.py", line 141, in flatten
    flatten_rs(input, output_dir, csv, xlsx, sqlite, parquet,
pyo3_runtime.PanicException: assertion failed: self.is_char_boundary(new_len)
```

**Comment by jpmckinney** [comment]
I'll try to upload a small file that reproduces the error. The current file is 77MB.

**Comment by jpmckinney** [comment]
Okay, here is a single JSONL line that causes the failure.
[test.txt](https://github.com/kindly/flatterer/files/14057372/test.txt)

**Comment by kindly** [comment]
@jpmckinney thanks for the report

The issue is due to trying to truncating those large cells for XLSX files and doing it in the middle of a Unicode characters.

I have a fix in libflatterer now:
https://github.com/kindly/libflatterer/commit/cd4fe9e57afde3e20a82c4bcbe579562c78cb276

I will try to get a release out in the next day or so.

**Comment by jpmckinney** [comment]
Thank you!
